// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztzlttcckorogkeripqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0emx0dGNja29yb2drZXJpcHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDUwNDksImV4cCI6MjA3MTUyMTA0OX0.mbzvpeTNQwQWyZHH19T-6iJI93TYTnQ3mSG6MgDBAhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});